#!/usr/bin/env bash
# Joyclare
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
#   Displays the IP and HTTP status code.

awk '{print $1 " " $9}' apache-access.log
